language: java
jdk:
- oraclejdk8
script:
- cd simple-test
- mvn clean verify

addons:
  ssh_known_hosts: jbosswildfly-web2msg.rhcloud.com
before_install:
- openssl aes-256-cbc -K $encrypted_98561ba32456_key -iv $encrypted_98561ba32456_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa

after_success:
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && mvn javadoc:javadoc && rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/simple-test/target/site 5731f51e89f5cfe33900001c@jbosswildfly-web2msg.rhcloud.com:/tmp
