language: java
jdk:
- oraclejdk8

install:
# Build iPST core
- git clone https://github.com/powsybl/powsybl-core powsybl/powsybl-core
- pushd powsybl/powsybl-core && mvn install && popd

script:
- cd simple-test
- mvn clean verify

addons:
  ssh_known_hosts: jbosswildfly-web2msg.rhcloud.com
  apt:
    packages:
      - graphviz
before_install:
- openssl aes-256-cbc -K $encrypted_98561ba32456_key -iv $encrypted_98561ba32456_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa

after_success:
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && mvn javadoc:javadoc && cd $TRAVIS_BUILD_DIR/simple-test/target/site/apidocs && zip -r /tmp/javadoc4.zip . && popd
- test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && cd $TRAVIS_BUILD_DIR/powsybl/powsybl-core && mvn javadoc:javadoc && cd target/site/apidocs && zip -r /tmp/powsybl-core-javadoc.zip . 
