language: java
jdk:
- oraclejdk8
script:
- cd simple-test
- mvn clean verify
after_success:
- mvn javadoc:javadoc
addons:
  ssh_known_hosts: jbosswildfly-web2msg.rhcloud.com
before_deploy:
- cd ..
- openssl aes-256-cbc -K $encrypted_98561ba32456_key -iv $encrypted_98561ba32456_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/simple-test/target/site 5731f51e89f5cfe33900001c@jbosswildfly-web2msg.rhcloud.com:/tmp
  on:
    branch: master
