language: java
jdk:
- oraclejdk8
script:
- cd simple-test
- mvn clean verify
after_success:
- mvn javadoc:javadoc
before_install:
- openssl aes-256-cbc -K $encrypted_e8b5fd854dea_key -iv $encrypted_e8b5fd854dea_iv
  -in id_rsa.enc -out id_rsa -d
